// mon-projet-angular/src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavbarComponent } from '../../components/navbar/navbar.component';
import { SidebarComponent } from '../../components/sidebar/sidebar.component';
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, NavbarComponent, SidebarComponent],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA] // Ajouter cette ligne

})
export class DashboardComponent {
  isSidebarCollapsed = false;

  toggleSidebar() {
    this.isSidebarCollapsed = !this.isSidebarCollapsed;
  }
}


<div class="dashboard-container">
  <app-navbar (sidebarToggle)="toggleSidebar()"></app-navbar> 

  <div class="main-content">
    <app-sidebar [isCollapsed]="isSidebarCollapsed"></app-sidebar> 

    <div class="content">
      <h1>Dashboard</h1>
      <p>Bienvenue sur le dashboard de votre application.</p>
    </div>
  </div>
</div>

// mon-projet-react/src/pages/Dashboard.jsx
import React, { useState } from "react"; // Ajout de useState
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import "../styles/Dashboard.css";

const Dashboard = () => {
  const [isCollapsed, setIsCollapsed] = useState(false);

  const toggleSidebar = () => {
    setIsCollapsed(!isCollapsed);
  };
  
  return (
    <div className="app">
      <Navbar toggleSidebar={toggleSidebar} />
      <div className="content">
        <Sidebar isCollapsed={isCollapsed} />
        <main className="main-content">
        </main>
      </div>
    </div>
  );
};

export default Dashboard;
