// mon-projet-angular/src/app/components/navbar/navbar.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
  @Output() sidebarToggle = new EventEmitter<void>(); // Événement pour la sidebar

  constructor(private router: Router) {}

  logout() {
    this.router.navigate(['/login']);
  }

  toggleSidebar() {
    this.sidebarToggle.emit(); // Envoie un événement pour changer l'état du sidebar
  }
}

<nav class="navbar">
  <div class="left-section">
    <button class="toggle-btn" (click)="toggleSidebar()">☰</button>
    <div class="logo">
      <img src="image.webp" alt="Logo" />
    </div>
  </div>

  <ul class="nav-links">
    <li>
      <button class="logout-btn" (click)="logout()">Logout</button>
    </li>
  </ul>
</nav>

// mon-projet-react/src/components/Navbar.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import "../styles/Navbar.css";
import logo from "../assets/image/image.webp";

const Navbar = ({ toggleSidebar }) => {
  const navigate = useNavigate();

  const handleLogout = () => {
    localStorage.removeItem("user");
    navigate("/login");
  };

  return (
    <nav className="navbar">
      <div className="navbar-left">
        <button className="toggle-btn" onClick={toggleSidebar}>☰</button>
        <div className="logo">
          <img src={logo} alt="Logo" />
        </div>
      </div>
      <ul className="nav-links">
        <li>
          <button className="logout-btn" onClick={handleLogout}>Logout</button>
        </li>
      </ul>
    </nav>
  );
};

export default Navbar;
