// mon-projet-react/src/components/Sidebar.jsx
import React from "react";
import "../styles/Sidebar.css";

const Sidebar = ({ isCollapsed }) => {
  return (
    <aside className={`sidebar ${isCollapsed ? "collapsed" : ""}`}>
      <ul>
        <li>
          <a href="/dashboard">
            <i className="fas fa-tachometer-alt"></i> Dashboard
          </a>
        </li>
        <li>
          <a href="/products">
            <i className="fas fa-boxes"></i> Products
          </a>
        </li>
        <li>
          <a href="/upload">
            <i className="fas fa-upload"></i> Upload File
          </a>
        </li>
      </ul>
    </aside>
  );
};

export default Sidebar;

// mon-projet-angular/src/app/components/sidebar/sidebar.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css'],
  imports: [CommonModule],  
  standalone: true,
})
export class SidebarComponent {
  @Input() isCollapsed = false;
}

<aside [class.collapsed]="isCollapsed" class="sidebar">
  <ul class="menu">
    <li>
      <a routerLink="/dashboard">
        <i class="fas fa-tachometer-alt"></i> <span *ngIf="!isCollapsed">Dashboard</span>
      </a>
    </li>
    <li>
      <a routerLink="/products">
        <i class="fas fa-boxes"></i> <span *ngIf="!isCollapsed">Products</span>
      </a>
    </li>
    <li>
      <a routerLink="/upload">
        <i class="fas fa-upload"></i> <span *ngIf="!isCollapsed">Upload File</span>
      </a>
    </li>
  </ul>
</aside>
