// mon-projet-react/src/pages/Auth.jsx
import { useEffect, useState } from "react";
import axios from "axios";
import { useNavigate, Link } from "react-router-dom";
import "../styles/Auth.css"; 
import logo from "../assets/image/image.webp"; 

const Auth = () => {
  const [isLoginMode, setIsLoginMode] = useState(true); 
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    if ( !email || !password) {
      alert("Tous les champs sont obligatoires !");
      return;
    }
    e.preventDefault();
    try {
      const { data } = await axios.get("http://localhost:5000/users");
      const user = data.find((u) => u.email === email && u.password === password);

      if (user) {
        localStorage.setItem("user", JSON.stringify(user)); 
        alert("Connexion réussie !");
        navigate("/dashboard");
      } else {
        alert("Identifiants incorrects !");
      }
    } catch (error) {
      console.error("Erreur de connexion", error);
    }
  };

  const handleSignup = async (e) => {
    e.preventDefault();
    if (!username || !email || !password) {
      alert("Tous les champs sont obligatoires !");
      return;
    }

    try {
      const { data } = await axios.get("http://localhost:5000/users");
      if (data.some((user) => user.email === email)) {
        alert("Cet email est déjà utilisé !");
        return;
      }

      await axios.post("http://localhost:5000/users", { username, email, password });
      alert("Inscription réussie !");
      navigate("/login");
      setIsLoginMode(true); 
    } catch (error) {
      console.error("Erreur lors de l'inscription", error);
    }
  };

  const handleModeChange = () => {
    setIsLoginMode((prevMode) => {
      const newMode = !prevMode;
      navigate(newMode ? "/login" : "/signup");
      return newMode;
    });
  };
  

  useEffect(() => {
    if (window.location.pathname === "/signup") {
      setIsLoginMode(false);
    } else {
      setIsLoginMode(true);
    }
  }, []);
  

  

  return (
    <div className="auth-container">
      <div className="auth-box">
        <img src={logo} alt="ENSET Logo" />
        <h2>{isLoginMode ? "Sign In" : "Sign Up"}</h2>
        <form onSubmit={isLoginMode ? handleLogin : handleSignup}>
          {!isLoginMode && (
            <input
              type="text"
              placeholder="Name"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
          )}
          <input
            type="email"
            placeholder="Login"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <input
            type="password"
            placeholder="Password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <button type="submit">{isLoginMode ? "Sign In" : "Sign Up"}</button>
        </form>
        <Link
          to="#"
          className="auth-link"
          onClick={handleModeChange} 
        >
          {isLoginMode ? "New User? Click to sign up !!" : "Already registered? Click to sign in !!"}
        </Link>
      </div>
    </div>
  );
};

export default Auth;

// mon-projet-angular/src/app/components/auth/auth.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../service/auth.service';
import { CommonModule } from '@angular/common'; // ✅ Corrige `*ngIf`
import { FormsModule } from '@angular/forms';   // ✅ Corrige `ngModel`
import { ActivatedRoute } from '@angular/router';
interface RouteData {
  mode: 'login' | 'signup'; // Le mode peut être soit 'login', soit 'signup'
}

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.css'],
  imports: [CommonModule, FormsModule], 
  standalone: true,
  // ✅ Ajoute CommonModule & FormsModule

})
export class AuthComponent {
  isLoginMode = true;
  username = '';
  email = '';
  password = '';

  constructor(private authService: AuthService, private router: Router,private route: ActivatedRoute) {}
  ngOnInit(): void {
    this.route.data.subscribe((data) => {
      const routeData = data as RouteData; // Forcer le typage
      this.isLoginMode = routeData.mode === 'login';
    });
  }
  

  toggleMode(event: Event) {
    event.preventDefault(); // Empêche le comportement par défaut du lien
    this.isLoginMode = !this.isLoginMode;
    if (this.isLoginMode) {
      this.router.navigate(['/login']);
    } else {
      this.router.navigate(['/signup']);
    }
  }

  login() {
    this.authService.login(this.email, this.password).subscribe((users: any[]) => {
      const user = users.find((u: any) => u.email === this.email && u.password === this.password);
      if (user) {
        localStorage.setItem('user', JSON.stringify(user));
        alert('Connexion réussie !');
        this.router.navigate(['/dashboard']);
      } else {
        alert('Identifiants incorrects !');
      }
    }, (error: any) => {
      console.error('Erreur de connexion', error);
    });
  }
  

  signup() {
    if (!this.username || !this.email || !this.password) {
      alert('Tous les champs sont obligatoires !');
      return;
    }
  
    this.authService.login(this.email, this.password).subscribe((users: any[]) => {
      if (users.some((user: any) => user.email === this.email)) {
        alert('Cet email est déjà utilisé !');
        return;
      }
  
      this.authService.signup(this.username, this.email, this.password).subscribe(() => {
        alert('Inscription réussie !');
        this.isLoginMode = true;
      }, (error: any) => {
        console.error('Erreur lors de l\'inscription', error);
      });
    });
  }
  
}

<div class="auth-container">
  <div class="auth-box">
    <img src="image.webp" alt="ENSET Logo">
    <h2>{{ isLoginMode ? 'Sign In' : 'Sign Up' }}</h2>
    
    <form (ngSubmit)="isLoginMode ? login() : signup()">
      <div *ngIf="!isLoginMode">
        <input type="text" placeholder="Name" [(ngModel)]="username" name="username" required />
      </div>
      <input type="email" placeholder="Login" [(ngModel)]="email" name="email" required />
      <input type="password" placeholder="Password" [(ngModel)]="password" name="password" required />
      
      <button type="submit">{{ isLoginMode ? 'Sign In' : 'Sign Up' }}</button>
    </form>

    <a href="#" class="auth-link" (click)="toggleMode($event)">
      {{ isLoginMode ? 'New User? Click to sign up !!' : 'Already registered? Click to sign in !!' }}
    </a>
  </div>
</div>
